version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ${ECR_REPOSITORY_URI}:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push ${ECR_REPOSITORY_URI}:latest
